# Generated by Django 4.1.2 on 2022-11-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartitem',
            table='CartItem',
        ),
    ]
